/**
 * Directorio real de La Gran Vía — 85 locales.
 *
 * GENERADO desde el directorio oficial (lagranvia.com.mx/1330-2/).
 * Los logos viven en /public/tenants y provienen del mismo sitio oficial.
 *
 * `verify: true` marcaría un giro deducido del nombre o del logo. Hoy no hay
 * ninguno: los cuatro pendientes se confirmaron con administración el
 * 2026-07-29, y Ardena se excluyó por cierre definitivo.
 *
 * `hoursNeedsReview: true` marca los locales cuyo horario viene desalineado
 * en el directorio oficial (más grupos de días que rangos de horario). En esos
 * casos se muestra el texto crudo en vez de inventar un emparejamiento.
 * `logoOnDark: true` marca logotipos claros sobre fondo transparente: se
 * renderizan sobre una placa oscura porque desaparecerían sobre la arena.
 */

export type Pillar = "prueba" | "consiente" | "visita" | "servicios";

export type Tenant = {
  slug: string;
  name: string;
  pillar: Pillar;
  /** Descriptor corto mostrado bajo el nombre. */
  tag: string;
  logo: string;
  logoOnDark: boolean;
  zone: string;
  phone: string;
  hours: { days: string; times: string }[];
  /** El horario oficial viene desalineado en origen — revisar antes de publicar. */
  hoursNeedsReview?: boolean;
  /** Giro deducido — confirmar con administración. */
  verify?: boolean;
};

export const TENANTS: Tenant[] = [
  {
    slug: "260-grill-bar",
    name: "260 Grill & Bar",
    pillar: "prueba",
    tag: "Grill & bar",
    logo: "/tenants/260-grill-bar.jpg",
    logoOnDark: false,
    zone: "Zona 10",
    phone: "(686) 104 1924",
    hours: [{"days": "Lun - Jue", "times": "14:00 - 00:00"}, {"days": "Vie", "times": "13:00 - 00:00"}, {"days": "Sáb", "times": "12:00 - 00:30"}, {"days": "Dom", "times": "12:00 - 00:00"}],
  },
  {
    slug: "alma-verde",
    name: "Alma Verde",
    pillar: "prueba",
    tag: "Restaurante saludable",
    logo: "/tenants/alma-verde.png",
    logoOnDark: false,
    zone: "Zona 7",
    phone: "(686) 516 1505",
    hours: [{"days": "Lun - Sáb", "times": "7:00 - 22:00"}, {"days": "Domingo", "times": "8:00 - 20:00"}],
  },
  {
    slug: "amoreme",
    name: "AmoreMe",
    pillar: "visita",
    tag: "Moda & accesorios",
    logo: "/tenants/amoreme.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 488 7771",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 21:00"}, {"days": "Domingo", "times": "12:00 - 20:00"}],
  },
  {
    slug: "ara-transportes",
    name: "ARA Transportes",
    pillar: "servicios",
    tag: "Logística & transporte",
    logo: "/tenants/ara-transportes.jpg",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 517 4394",
    hours: [{"days": "Lun - Vie", "times": "08:00 - 18:00"}],
  },
  {
    slug: "ary-casa-de-novias",
    name: "Ary Casa de Novias",
    pillar: "visita",
    tag: "Novias & fiesta",
    logo: "/tenants/ary-casa-de-novias.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 355 7534",
    hours: [{"days": "Lun - Vie", "times": "13:00 - 19:00"}, {"days": "Sáb", "times": "11:00 - 17:00"}],
  },
  {
    slug: "ashley",
    name: "Ashley",
    pillar: "visita",
    tag: "Muebles & hogar",
    logo: "/tenants/ashley.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(663) 153 7173",
    hours: [{"days": "Mar - Dom", "times": "15:00 - 22:00"}],
  },
  {
    slug: "asian-wok-box",
    name: "Asian Wok Box",
    pillar: "prueba",
    tag: "Comida asiática",
    logo: "/tenants/asian-wok-box.png",
    logoOnDark: false,
    zone: "Zona 4",
    phone: "(686) 516 7272",
    hours: [{"days": "Lun - Dom", "times": "09:00 - 22:00"}],
  },
  {
    slug: "at-t",
    name: "AT&T",
    pillar: "servicios",
    tag: "Telefonía",
    logo: "/tenants/at-t.jpg",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 405 4490 · (686) 117 3951",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 19:00"}, {"days": "Sáb - Dom", "times": "10:00 - 18:00"}],
  },
  {
    slug: "axa",
    name: "AXA",
    pillar: "servicios",
    tag: "Seguros",
    logo: "/tenants/axa.png",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 557 1010",
    hours: [{"days": "Lun - Vie", "times": "8:00 - 14:00"}],
  },
  {
    slug: "baja-brunch",
    name: "Baja Brunch",
    pillar: "prueba",
    tag: "Brunch",
    logo: "/tenants/baja-brunch.jpg",
    logoOnDark: false,
    zone: "Zona 3",
    phone: "(686) 488 7592",
    hours: [{"days": "Lun - Vie", "times": "7:30 - 13:00"}, {"days": "Sáb", "times": "8:30 - 13:00"}, {"days": "Domingo", "times": "8:30 - 13:30"}],
  },
  {
    slug: "banorte",
    name: "Banorte",
    pillar: "servicios",
    tag: "Banco",
    logo: "/tenants/banorte.jpg",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 564 1453",
    hours: [{"days": "Lun - Vie", "times": "8:30 - 16:00"}],
  },
  {
    slug: "banregio",
    name: "Banregio",
    pillar: "servicios",
    tag: "Banco",
    logo: "/tenants/banregio.jpg",
    logoOnDark: false,
    zone: "Zona 4",
    phone: "(686) 514 3380",
    hours: [{"days": "Lun - Vie", "times": "9:00 - 16:00"}],
  },
  {
    slug: "be-a-lash-girl",
    name: "Be a Lash Girl",
    pillar: "consiente",
    tag: "Extensiones de pestañas",
    logo: "/tenants/be-a-lash-girl.jpg",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 516 6466 (686) 415 4060",
    hours: [{"days": "Lun - Vie", "times": "8:00 - 20:00"}, {"days": "Sábado", "times": "9:00 - 18:00"}, {"days": "Domingo", "times": "10:00 - 17:00"}],
  },
  {
    slug: "best-optical",
    name: "Best Optical",
    pillar: "visita",
    tag: "Óptica",
    logo: "/tenants/best-optical.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 514 3355",
    hours: [{"days": "Dom - Vie", "times": "10:00 - 18:00"}],
  },
  {
    slug: "blue-luna-cafe",
    name: "Blue Luna Café",
    pillar: "prueba",
    tag: "Café & deli",
    logo: "/tenants/blue-luna-cafe.png",
    logoOnDark: false,
    zone: "Zona 4",
    phone: "(686) 104 3271",
    hours: [{"days": "Lun - Sáb", "times": "6:30 - 22:30"}, {"days": "Domingo", "times": "8:00 - 21:00"}],
  },
  {
    slug: "bodega-8",
    name: "Bodega 8",
    pillar: "prueba",
    tag: "Restaurante & bar",
    logo: "/tenants/bodega-8.png",
    logoOnDark: false,
    zone: "Zona 7",
    phone: "(686) 514 3445",
    hours: [{"days": "Lun - Mar", "times": "12:00 - 23:00"}, {"days": "Mié - Sáb", "times": "12:00 - 00:00"}, {"days": "Domingo", "times": "12:00 - 22:00"}],
  },
  {
    slug: "bonaprime",
    name: "Bonaprime",
    pillar: "prueba",
    tag: "Steakhouse",
    logo: "/tenants/bonaprime.jpg",
    logoOnDark: false,
    zone: "Zona 4",
    phone: "(686) 564 5069",
    hours: [{"days": "Lun - Jue", "times": "09:00 - 18:00"}, {"days": "Vie - Sáb", "times": "09:00 - 19:00"}, {"days": "Domingo", "times": "10:00 - 18:00"}],
  },
  {
    slug: "buffalo-wild-wings",
    name: "Buffalo Wild Wings",
    pillar: "prueba",
    tag: "Alitas & deportes",
    logo: "/tenants/buffalo-wild-wings.jpg",
    logoOnDark: false,
    zone: "Zona 10",
    phone: "(686) 514 3431",
    hours: [{"days": "Dom - Mié", "times": "12:00 - 22:00"}, {"days": "Jue - Sáb", "times": "12:00 - 23:00"}],
  },
  {
    slug: "cabanna",
    name: "Cabanna",
    pillar: "prueba",
    tag: "Restaurante",
    logo: "/tenants/cabanna.png",
    logoOnDark: false,
    zone: "Zona 4",
    phone: "(686) 905 0203 · (686) 905 0318",
    hours: [{"days": "Lun - Jue", "times": "11:00 - 22:00"}, {"days": "Vie - Sáb", "times": "11:00 - 23:00"}, {"days": "Domingo", "times": "11:00 - 20:00"}],
  },
  {
    slug: "choys-moda-infantil",
    name: "Choys Moda Infantil",
    pillar: "visita",
    tag: "Moda infantil",
    logo: "/tenants/choys-moda-infantil.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 188 4528",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 18:00"}],
  },
  {
    slug: "cinemex-premium",
    name: "Cinemex Premium",
    pillar: "visita",
    tag: "Cine premium",
    logo: "/tenants/cinemex-premium.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(800) 710 8888",
    hours: [{"days": "Lun - Dom", "times": "13:00 - 20:00"}],
  },
  {
    slug: "dentyx-clinica-dental",
    name: "Dentyx Clínica Dental",
    pillar: "consiente",
    tag: "Clínica dental",
    logo: "/tenants/dentyx-clinica-dental.jpg",
    logoOnDark: false,
    zone: "Zona 6 segundo piso",
    phone: "(686) 203 3482",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 19:00"}, {"days": "Sáb", "times": "9:00 - 14:00"}],
  },
  {
    slug: "derma-club-farmacia-dermatologica",
    name: "Derma Club Farmacia Dermatológica",
    pillar: "consiente",
    tag: "Farmacia dermatológica",
    logo: "/tenants/derma-club-farmacia-dermatologica.png",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 517 8275",
    hours: [{"days": "Lun - Vie", "times": "11:00 - 19:00"}],
  },
  {
    slug: "devoralia",
    name: "Devoralia",
    pillar: "prueba",
    tag: "Comedor urbano",
    logo: "/tenants/devoralia.png",
    logoOnDark: true,
    zone: "Zona 2",
    phone: "(686) 565 0281",
    hours: [{"days": "Lun - Vie", "times": "11:00 - 22:00"}, {"days": "Sáb - Dom", "times": "12:00 - 22:00"}],
  },
  {
    slug: "dra-claudia-h-machuca",
    name: "Dra. Claudia H. Machuca",
    pillar: "consiente",
    tag: "Consultorio médico",
    logo: "/tenants/dra-claudia-h-machuca.png",
    logoOnDark: false,
    zone: "Zona 3",
    phone: "(686) 116 1268",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 16:00"}],
  },
  {
    slug: "etcetera-accesorios",
    name: "Etcétera Accesorios",
    pillar: "visita",
    tag: "Accesorios",
    logo: "/tenants/etcetera-accesorios.png",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 488 7768",
    hours: [{"days": "Lun - Dom", "times": "10:00 - 21:00"}],
  },
  {
    slug: "fairfield-inn-suites-by-marriott",
    name: "Fairfield Inn & Suites by Marriott",
    pillar: "visita",
    tag: "Hospedaje",
    logo: "/tenants/fairfield-inn-suites-by-marriott.jpg",
    logoOnDark: false,
    zone: "Zona 8",
    phone: "(686) 200 0150",
    hours: [{"days": "Lun - Dom", "times": "Siempre Abierto"}],
  },
  {
    slug: "femgraphy",
    name: "Femgraphy",
    pillar: "consiente",
    tag: "Imagenología femenina",
    logo: "/tenants/femgraphy.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 213 5561",
    hours: [{"days": "Lun Mar - Jue Vie Sáb Dom", "times": "08:00 - 20:00 08:00 - 19:00 10:00 - 18:00 13:00 - 17:00"}],
    hoursNeedsReview: true,
  },
  {
    slug: "flavor-cup",
    name: "Flavor Cup",
    pillar: "prueba",
    tag: "Postres & bebidas",
    logo: "/tenants/flavor-cup.png",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 488 7758",
    hours: [{"days": "Lun - Dom", "times": "11:00 - 22:30"}],
  },
  {
    slug: "french-place",
    name: "French Place",
    pillar: "prueba",
    tag: "Tacos & cocina",
    logo: "/tenants/french-place.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 187 1218⁩",
    hours: [{"days": "Lun - Vie", "times": "12:00 - 22:00"}, {"days": "Sáb", "times": "13:00 - 22:00"}, {"days": "Domingo", "times": "14:00 - 20:00"}],
  },
  {
    slug: "grace-nails-beauty",
    name: "Grace Nails & Beauty",
    pillar: "consiente",
    tag: "Uñas & beauty",
    logo: "/tenants/grace-nails-beauty.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 517 0850",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 20:00"}, {"days": "Domingo", "times": "11:00 - 19:00"}],
  },
  {
    slug: "hermez-diseno-y-construccion",
    name: "Hermez Diseño y Construcción",
    pillar: "servicios",
    tag: "Diseño & construcción",
    logo: "/tenants/hermez-diseno-y-construccion.jpg",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 552 30 02",
    hours: [{"days": "Lun - Vie", "times": "8:00 - 15:00"}],
  },
  {
    slug: "holiday-inn-express",
    name: "Holiday Inn Express",
    pillar: "visita",
    tag: "Hospedaje",
    logo: "/tenants/holiday-inn-express.jpg",
    logoOnDark: false,
    zone: "Zona 8",
    phone: "(686) 841 8100",
    hours: [{"days": "Lun - Dom", "times": "Siempre Abierto"}],
  },
  {
    slug: "holy-cow",
    name: "Holy Cow",
    pillar: "prueba",
    tag: "Burger & beer joint",
    logo: "/tenants/holy-cow.png",
    logoOnDark: false,
    zone: "Zona 1",
    phone: "(686) 104 1411",
    hours: [{"days": "Lun - Dom", "times": "12:00 - 24:00"}],
  },
  {
    slug: "ihop",
    name: "IHOP",
    pillar: "prueba",
    tag: "Desayunos",
    logo: "/tenants/ihop.png",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 488 7778",
    hours: [{"days": "Lun - Dom", "times": "7:00 - 15:00"}],
  },
  {
    slug: "ixchel",
    name: "Ixchel",
    pillar: "visita",
    tag: "Arte e identidad mexicana",
    logo: "/tenants/ixchel.jpg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 522 3513",
    hours: [{"days": "Lun - Sáb", "times": "9:00 - 22:00"}, {"days": "Domingo", "times": "9:00 - 21:00"}],
  },
  {
    slug: "karen-carrillo",
    name: "Karen Carrillo",
    pillar: "consiente",
    tag: "Medicina estética",
    logo: "/tenants/karen-carrillo.jpg",
    logoOnDark: false,
    zone: "Zona 8",
    phone: "Tel (686) 517 4628 · WA (686) 945 1477",
    hours: [{"days": "Lun - Vie", "times": "9:00 - 20:00"}],
  },
  {
    slug: "katana-manga-shop",
    name: "Katana Manga Shop",
    pillar: "visita",
    tag: "Manga & coleccionables",
    logo: "/tenants/katana-manga-shop.webp",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 459 5509",
    hours: [{"days": "Lun - Dom", "times": "11:00 - 20:00"}],
  },
  {
    slug: "kidsquad",
    name: "KidSquad",
    pillar: "visita",
    tag: "Juegos infantiles",
    logo: "/tenants/kidsquad.png",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "6865174628 WA: 6869451477",
    hours: [{"days": "Mar - Vie", "times": "14:00 - 21:00"}, {"days": "Sáb - Dom", "times": "12:00 - 21:00"}],
  },
  {
    slug: "koori",
    name: "Koori",
    pillar: "prueba",
    tag: "Cocina japonesa",
    logo: "/tenants/koori.png",
    logoOnDark: false,
    zone: "Zona 3",
    phone: "(686) 160 5184",
    hours: [{"days": "Lun - Jue", "times": "13:30 - 22:00"}, {"days": "Vie - Sáb", "times": "13:30 - 23:30"}, {"days": "Domingo", "times": "13:30 - 20:30"}],
  },
  {
    slug: "la-grieguita",
    name: "La Grieguita",
    pillar: "prueba",
    tag: "Gyros & cocina griega",
    logo: "/tenants/la-grieguita.png",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 565 0860",
    hours: [{"days": "Lun - Vie", "times": "11:00 - 22:00"}, {"days": "Sáb - Dom", "times": "12:00 - 21:00"}],
  },
  {
    slug: "lady-bug",
    name: "Lady Bug",
    pillar: "visita",
    tag: "Boutique infantil",
    logo: "/tenants/lady-bug.png",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 547 5934 · (686) 514 3393",
    hours: [{"days": "Lun - Sáb", "times": "10:00 - 20:00"}],
  },
  {
    slug: "look-optica",
    name: "Look Óptica",
    pillar: "visita",
    tag: "Óptica",
    logo: "/tenants/look-optica.png",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 488 7764",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 20:00"}, {"days": "Domingo", "times": "13:00 - 20:00"}],
  },
  {
    slug: "luuna",
    name: "Luuna",
    pillar: "visita",
    tag: "Colchones & descanso",
    logo: "/tenants/luuna.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "686 598 5567",
    hours: [{"days": "Lun - Dom", "times": "10:30 - 21:00"}],
  },
  {
    slug: "mae-boutique",
    name: "Mae Boutique",
    pillar: "visita",
    tag: "Boutique",
    logo: "/tenants/mae-boutique.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "686 111 7468",
    hours: [{"days": "Lun - Sáb", "times": "10:00 - 20:00"}],
  },
  {
    slug: "maja",
    name: "Maja",
    pillar: "visita",
    tag: "Ropa outdoor",
    logo: "/tenants/maja.svg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 517 2414",
    hours: [{"days": "Lun - Dom", "times": "10:00 - 20:00"}],
  },
  {
    slug: "maktub",
    name: "Maktub",
    pillar: "visita",
    tag: "Boutique",
    logo: "/tenants/maktub.jpg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 457 9941",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 20:00"}],
  },
  {
    slug: "maraki-poke",
    name: "Maraki Poke",
    pillar: "prueba",
    tag: "Poke to-go",
    logo: "/tenants/maraki-poke.png",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 514 3539",
    hours: [{"days": "Lun - Sáb", "times": "12:00 - 21:00"}, {"days": "Domingo", "times": "13:00 - 21:00"}],
  },
  {
    slug: "masari-casa-de-bolsa",
    name: "Masari Casa de Bolsa",
    pillar: "servicios",
    tag: "Casa de bolsa",
    logo: "/tenants/masari-casa-de-bolsa.jpg",
    logoOnDark: false,
    zone: "Zona 3 segundo piso",
    phone: "(664) 748 0600",
    hours: [{"days": "Lun - Vie", "times": "8:00 - 17:00"}],
  },
  {
    slug: "mi-corazon-hermoso",
    name: "Mi Corazón Hermoso",
    pillar: "visita",
    tag: "Regalos & detalles",
    logo: "/tenants/mi-corazon-hermoso.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 576 8634",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 18:00"}],
  },
  {
    slug: "mint-boutique",
    name: "MINT Boutique",
    pillar: "visita",
    tag: "Moda mujer",
    logo: "/tenants/mint-boutique.png",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "No Disponible",
    hours: [{"days": "Lun - Sáb", "times": "9:30 - 20:30"}],
  },
  {
    slug: "minue-studio",
    name: "Minué Studio",
    pillar: "consiente",
    tag: "Estudio de belleza",
    logo: "/tenants/minue-studio.jpg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 841 1959",
    hours: [{"days": "Lun - Sáb", "times": "5:00 - 11:30 15:30 - 21:30"}],
    hoursNeedsReview: true,
  },
  {
    slug: "nice-factory-of-beauty",
    name: "Nice Factory of Beauty",
    pillar: "consiente",
    tag: "Salón de belleza",
    logo: "/tenants/nice-factory-of-beauty.jpg",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 463 4872",
    hours: [{"days": "Lun - Sáb", "times": "8:00 - 19:00"}],
  },
  {
    slug: "novamoda",
    name: "NOVAMODA",
    pillar: "visita",
    tag: "Boutique",
    logo: "/tenants/novamoda.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 426 1879",
    hours: [{"days": "Lun - Sáb", "times": "10:00 - 20:00"}, {"days": "Domingo", "times": "10:00 - 18:00"}],
  },
  {
    slug: "pagoda-cocina-china",
    name: "Pagoda Cocina China",
    pillar: "prueba",
    tag: "Cocina china",
    logo: "/tenants/pagoda-cocina-china.jpg",
    logoOnDark: false,
    zone: "Zona 8",
    phone: "(686) 516 3233",
    hours: [{"days": "Lunes", "times": "11:00 - 21:00"}, {"days": "Mar - Dom", "times": "11:00 - 22:00"}],
  },
  {
    slug: "paloma-s-interiors",
    name: "Paloma's Interiors",
    pillar: "visita",
    tag: "Interiorismo",
    logo: "/tenants/paloma-s-interiors.jpg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 565 7507",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 19:00"}, {"days": "Sáb - Dom", "times": "10:00 - 17:00"}],
  },
  {
    slug: "pavi-italy",
    name: "Pavi Italy",
    pillar: "visita",
    tag: "Calzado italiano",
    logo: "/tenants/pavi-italy.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 488 7765",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 20:00"}, {"days": "Domingo", "times": "13:00 - 18:00"}],
  },
  {
    slug: "perpetua-joyeros",
    name: "Perpetua Joyeros",
    pillar: "visita",
    tag: "Joyería",
    logo: "/tenants/perpetua-joyeros.jpg",
    logoOnDark: false,
    zone: "Zona 2",
    phone: "(686) 586 4426",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 20:00"}, {"days": "Sábado", "times": "11:00 - 16:00"}],
  },
  {
    slug: "petco",
    name: "PETCO",
    pillar: "visita",
    tag: "Mascotas",
    logo: "/tenants/petco.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 837 9147 · (686) 837 9148",
    hours: [{"days": "Lun - Dom", "times": "8:00 - 21:00"}],
  },
  {
    slug: "pily-camacho-salon-capilar",
    name: "Pily Camacho Salón Capilar",
    pillar: "consiente",
    tag: "Salón capilar",
    logo: "/tenants/pily-camacho-salon-capilar.jpg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "686 5855556",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 19:00"}, {"days": "Dom", "times": "10:00 - 18:00"}],
  },
  {
    slug: "proaktiva",
    name: "Proaktiva",
    pillar: "servicios",
    tag: "Servicios empresariales",
    logo: "/tenants/proaktiva.png",
    logoOnDark: false,
    zone: "Zona 6 segundo piso",
    phone: "(686) 234 6776 · (686) 553 4500",
    hours: [{"days": "Lun - Vie", "times": "08:00 - 18:00"}],
  },
  {
    slug: "remax-sh-deluxe",
    name: "REMAX SH Deluxe",
    pillar: "servicios",
    tag: "Bienes raíces",
    logo: "/tenants/remax-sh-deluxe.jpg",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 488 7788",
    hours: [{"days": "Lun - Sáb", "times": "9:00 - 18:00"}, {"days": "Domingo", "times": "10:00 - 17:00"}],
  },
  {
    slug: "rocio-beauty-treatment",
    name: "Rocio Beauty Treatment",
    pillar: "consiente",
    tag: "Tratamientos de belleza",
    logo: "/tenants/rocio-beauty-treatment.jpg",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "686 235 9955",
    hours: [{"days": "Lun - Vie", "times": "9:00 - 20:00"}, {"days": "Sábado", "times": "9:00 - 15:00"}],
  },
  {
    slug: "rose",
    name: "Rosé",
    pillar: "visita",
    tag: "Boutique",
    logo: "/tenants/rose.png",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 488 7763",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 20:00"}, {"days": "Domingo", "times": "14:00 - 20:00"}],
  },
  {
    slug: "sabrosisimo",
    name: "Sabrosisimo",
    pillar: "prueba",
    tag: "Cocina casera",
    logo: "/tenants/sabrosisimo.jpg",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 112 1869",
    hours: [{"days": "Lun - Dom", "times": "10:00 - 20:00"}],
  },
  {
    slug: "santander",
    name: "Santander",
    pillar: "servicios",
    tag: "Banco",
    logo: "/tenants/santander.png",
    logoOnDark: false,
    zone: "Zona 4",
    phone: "(686) 564 5914",
    hours: [{"days": "Lun - Vie", "times": "09:00 - 16:00"}],
  },
  {
    slug: "shoeblime",
    name: "Shoeblime",
    pillar: "visita",
    tag: "Calzado",
    logo: "/tenants/shoeblime.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 569 4443",
    hours: [{"days": "Lun - Sáb", "times": "11:00 - 20:00"}, {"days": "Domingo", "times": "11:00 - 19:00"}],
  },
  {
    slug: "smilers",
    name: "Smilers",
    pillar: "consiente",
    tag: "Clínica dental",
    logo: "/tenants/smilers.png",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 111 8804",
    hours: [{"days": "Lun - Vie", "times": "09:00 - 19:00"}, {"days": "Sábado", "times": "09:00 - 18:00"}],
  },
  {
    slug: "subway",
    name: "Subway",
    pillar: "prueba",
    tag: "Sándwiches",
    logo: "/tenants/subway.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 5145584",
    hours: [{"days": "Lun - Dom", "times": "9:00 - 22:00"}],
  },
  {
    slug: "symmetria-arquitectura",
    name: "Symmetria Arquitectura",
    pillar: "servicios",
    tag: "Arquitectura",
    logo: "/tenants/symmetria-arquitectura.jpg",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 216 4534",
    hours: [{"days": "Lun - Vie", "times": "8:30 - 18:30"}],
  },
  {
    slug: "symmetry-gym-mexicali",
    name: "SYMMETRY GYM Mexicali",
    pillar: "consiente",
    tag: "Gimnasio",
    logo: "/tenants/symmetry-gym-mexicali.jpg",
    logoOnDark: false,
    zone: "Zona 9 interior",
    phone: "(686) 517 9168",
    hours: [{"days": "Lun - Sáb", "times": "05:00 - 23:00"}, {"days": "Domingo", "times": "07:00 - 16:00"}],
  },
  {
    slug: "telcel",
    name: "Telcel",
    pillar: "servicios",
    tag: "Telefonía",
    logo: "/tenants/telcel.png",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 488 7761",
    hours: [{"days": "Lun - Vie", "times": "9:00 - 19:00"}, {"days": "Sábado", "times": "9:00 - 16:00"}],
  },
  {
    slug: "the-cakery",
    name: "The Cakery",
    pillar: "prueba",
    tag: "Pastelería",
    logo: "/tenants/the-cakery.jpg",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 576 9553",
    hours: [{"days": "Lun", "times": "12:30 - 20:00"}, {"days": "Mar - Sáb", "times": "9:00 - 21:00"}, {"days": "Domingo", "times": "9:00 - 19:00"}],
  },
  {
    slug: "thrifty-ice-cream",
    name: "Thrifty Ice Cream",
    pillar: "prueba",
    tag: "Helados",
    logo: "/tenants/thrifty-ice-cream.png",
    logoOnDark: false,
    zone: "Zona 10",
    phone: "(686) 488 7769",
    hours: [{"days": "Lun - Dom", "times": "11:00 - 20:00"}],
  },
  {
    slug: "timeless-medcenter",
    name: "Timeless Medcenter",
    pillar: "consiente",
    tag: "Medicina estética",
    logo: "/tenants/timeless-medcenter.png",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 248 9184",
    hours: [{"days": "Lun - Vie", "times": "9:00 - 19:00"}, {"days": "Sáb", "times": "10:00 - 14:00"}],
  },
  {
    slug: "tavola-trattoria",
    name: "Távola Trattoría",
    pillar: "prueba",
    tag: "Trattoria italiana",
    logo: "/tenants/tavola-trattoria.png",
    logoOnDark: false,
    zone: "Zona 2",
    phone: "(686) 565 1016",
    hours: [{"days": "Lun - Mié", "times": "08:00 - 23:00"}, {"days": "Jue - Sáb", "times": "08:00 - 00:00"}, {"days": "Domingo", "times": "08:00 - 20:00"}],
  },
  {
    slug: "uniformes-cisne",
    name: "Uniformes Cisne",
    pillar: "servicios",
    tag: "Uniformes",
    logo: "/tenants/uniformes-cisne.png",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(686) 216 4783",
    hours: [{"days": "Lun - Vie", "times": "10:00 - 19:00"}, {"days": "Sáb", "times": "10:00 - 16:00"}],
  },
  {
    slug: "urban-clean",
    name: "Urban Clean",
    pillar: "servicios",
    tag: "Tintorería",
    logo: "/tenants/urban-clean.png",
    logoOnDark: false,
    zone: "Zona 9",
    phone: "(686) 514 3372",
    hours: [{"days": "Lunes", "times": "7:00 - 19:00"}, {"days": "Mar - Vie", "times": "9:00 - 19:00"}, {"days": "Sábado", "times": "9:00 - 14:00"}],
  },
  {
    slug: "victor-rodiles",
    name: "Victor Rodiles",
    pillar: "servicios",
    tag: "Arquitectura",
    logo: "/tenants/victor-rodiles.jpg",
    logoOnDark: false,
    zone: "Zona 5",
    phone: "(686) 329 0957",
    hours: [{"days": "Lun - Vie", "times": "8:00 - 17:00"}, {"days": "Sáb", "times": "9:00 - 13:00"}],
  },
  {
    slug: "vinos-tras-lupita",
    name: "Vinos Tras Lupita",
    pillar: "prueba",
    tag: "Vinos & bar",
    logo: "/tenants/vinos-tras-lupita.png",
    logoOnDark: false,
    zone: "Zona 10",
    phone: "(686) 516 2981",
    hours: [{"days": "Lun - Mar", "times": "11:00 - 22:00"}, {"days": "Mié - Sáb", "times": "11:00 - 22:45"}],
  },
  {
    slug: "wendlandt-tasting-room",
    name: "Wendlandt Tasting Room",
    pillar: "prueba",
    tag: "Cervecería artesanal",
    logo: "/tenants/wendlandt-tasting-room.jpg",
    logoOnDark: false,
    zone: "Zona 6",
    phone: "(646)1747060",
    hours: [{"days": "Mar - Mié", "times": "17:00 - 24:00"}, {"days": "Jue - Sáb", "times": "17:00 - 1:00"}, {"days": "Domingo", "times": "14:00 - 22:00"}],
  },
  {
    slug: "wrap-roll",
    name: "Wrap & Roll",
    pillar: "prueba",
    tag: "Wraps & saludable",
    logo: "/tenants/wrap-roll.jpg",
    logoOnDark: false,
    zone: "Zona 3",
    phone: "(686) 514 1857",
    hours: [{"days": "Lun - Vie", "times": "9:00 - 23:00"}, {"days": "Sáb - Dom", "times": "9:00 - 22:00"}],
  },
  {
    slug: "zero-depilacion",
    name: "Zero Depilación",
    pillar: "consiente",
    tag: "Depilación láser",
    logo: "/tenants/zero-depilacion.jpg",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 524 9956",
    hours: [{"days": "Lun - Vie", "times": "8:00 - 21:00"}, {"days": "Sáb", "times": "8:00 - 16:00"}, {"days": "Domingo", "times": "10:00 - 18:00"}],
  },
  {
    slug: "zpin-lab",
    name: "Zpin Lab",
    pillar: "consiente",
    tag: "Cycling & fitness",
    logo: "/tenants/zpin-lab.png",
    logoOnDark: false,
    zone: "Zona 9 segundo piso",
    phone: "(686) 104 8793",
    hours: [{"days": "Lun, Mar, Mié, Jue Vie Sáb Dom", "times": "6:30 - 9:15 AM, 5:30 - 9 PM 6:30 - 9:15 AM, 5:30 - 8 PM 6:30 - 9:15 AM, 5:30 - 9 PM 6:30 - 9:15 AM, 5:30 - 8 PM 8 - 9:15 AM, 5:30 - 7 PM 9:30 AM - 12 PM 9:30 - 11 AM"}],
    hoursNeedsReview: true,
  },
];

export const PILLAR_LABELS: Record<Pillar, { kicker: string; en: string; title: string; desc: string }> = {
  prueba: {
    kicker: "PRUEBA",
    en: "Taste",
    title: "Gastronomía & buena vida",
    desc: "Restaurantes, cafés y bares para cada antojo.",
  },
  consiente: {
    kicker: "CONSIÉNTETE",
    en: "Pamper",
    title: "Bienestar & belleza",
    desc: "Fitness, spa y estética para reconectar.",
  },
  visita: {
    kicker: "VISITA",
    en: "Explore",
    title: "Cultura & retail",
    desc: "Cine, hoteles y tiendas para explorar.",
  },
  servicios: {
    kicker: "RESUELVE",
    en: "Services",
    title: "Bancos & servicios",
    desc: "Banca, telefonía y servicios profesionales.",
  },
};

export const tenantsByPillar = (pillar: Pillar) =>
  TENANTS.filter((t) => t.pillar === pillar);

